// @ts-check
import { defineConfig } from 'astro/config';
import react from '@astrojs/react';
import tailwindcss from '@tailwindcss/vite';
import sitemap from '@astrojs/sitemap';

// https://astro.build/config
export default defineConfig({
  site: 'https://goodside.fi/',
  i18n: {
    defaultLocale: 'fi',
    locales: ['fi', 'en'],
    routing: {
      prefixDefaultLocale: false
    }
  },
  integrations: [
    react(),
    sitemap()
  ],
  redirects: {
    '/in-english/': '/en/',
    '/fi/in-english/': '/en/',
    '/palvelumuotoilu-kuntien-ja-kaupunkien-kehittamisen-tukena/': '/fi/blog/palvelumuotoilu-kuntien-kehittamisessa/',
    '/fi/palvelumuotoilu-kuntien-ja-kaupunkien-kehittamisen-tukena/': '/fi/blog/palvelumuotoilu-kuntien-kehittamisessa/',
    '/design-thinking-prosessi-joka-sytyttaa-luovuuden-liekin/': '/fi/blog/design-thinking-prosessi-joka-sytyttaa-luovuuden-liekinfi/',
    '/blogi/': '/fi/blog/',
    '/hyvan-kehityskeskustelun-malli/': '/fi/blog/',
    '/insinoorilahtoisyys-uhka-vai-mahdollisuus/': '/fi/blog/insinoorilahtoisyys-uhka-vai-mahdollisuusfi/',
    '/empatia-palvelumuotoilussa/': '/fi/blog/empatia-palvelumuotoilussafi/',
    '/kaytettavyys-ja-ergonomia-sujuvan-ja-terveellisen-tyoskentelyn-perusta/': '/fi/blog/kaytettavyys-ja-ergonomia-sujuvan-ja-terveellisen-tyoskentelyn-perustafi/',
    '/palvelumuotoilun-hyodyt/': '/fi/blog/mita-hyotya-on-palvelumuotoilusta/',
    '/taydellinen-landing-page/': '/fi/blog/taydellisen-laskeutumissivun-suunnittelu/',
    '/nain-kehitat-sisaista-viestintaa/': '/fi/blog/nain-kehitat-sisaista-viestintaa/',
    '/design-thinking-menestyvien-organisaatioiden-salainen-ainesosa/': '/fi/blog/design-thinking-menestyvien-organisaatioiden-salainen-ainesosa/',
    '/blog/jakob-nielsen-ja-kaytettavyyden-periaatteet/': '/fi/blog/jakob-nielsen-ja-kaytettavyyden-periaatteetfi/',
    '/ux-ja-uxr/': '/fi/blog/ux-ja-uxr/',
    '/mita-on-palvelumuotoilu/': '/fi/blog/mita-on-palvelumuotoilufi/',
    '/mobiilisovelluksen-ui-ux-suunnittelu/': '/fi/blog/mobiilisovelluksen-ui-ux-suunnittelufi/',
    '/prototyyppi-ideasta-toimivaksi-tuotteeksi/': '/fi/blog/prototyyppi-ideasta-toimivaksi-tuotteeksifi/',
    '/suosituimmat-kayttajatutkimusmenetelmat/': '/fi/blog/ux-ja-uxrfi/',
    '/ideasta-appiin-selviytymisopas-kun-osaat-bisneksen-mutta-et-bittia/': '/fi/blog/ideasta-appiin-selviytymisopasfi/',
    '/ux-ja-ui-suunnittelu-mita-ne-ovat/': '/fi/blog/ux-ja-ui-suunnittelu-mita-ne-ovatfi/',
    '/ideasta-appiin-selviytymisopas/': '/fi/blog/ideasta-appiin-selviytymisopasfi/',
    '/tuotemuotoilun-karjessa/': '/fi/blog/tuotemuotoilun-karjessa/',
    '/kayttajatestaus-tekoalyn-avulla/': '/fi/blog/kayttajatestaus-tekoalyn-avulla/',
    '/design-velan-korko/': '/fi/blog/design-velan-korkofi/',
    '/palvelumuotoilu-insinoorivetoisten-organisaatioiden-tukena/': '/fi/blog/palvelumuotoilu-insinoorivetoisten-organisaatioiden-tukenafi/',
    '/kaytettavyys-ohjelmistokehityksessa/': '/fi/blog/kaytettavyys-ohjelmistokehityksessafi/',
    '/ux-suunnittelun-lait/': '/fi/blog/ux-suunnittelun-laitfi/',
    '/ux-suunnittelun-arvo/': '/fi/blog/ux-suunnittelun-arvofi/',
    '/tekoaly-ja-uxr/': '/fi/blog/tekoaly-ja-uxrfi/',
    '/konversio-optimointi-ja-top5-vinkit/': '/fi/blog/konversio-optimointi-ja-top5-vinkitfi/',
    '/designin-yhtenaisyys-muutosten-keskella/': '/fi/blog/designin-yhtenaisyys-muutosten-keskellafi/',
    '/mista-muodostuu-hyva-kayttokokemus-10-tekijaa/': '/fi/blog/mista-muodostuu-hyva-kayttokokemus-10-tekijaafi/',
    '/prototyypin-testaaminen/': '/fi/blog/prototyypin-testaaminenfi/',
    '/category/ux/': '/fi/blog/',
    '/tiimi/oppaat/': '/fi/blog/',
    '/george-burchett-maailman-ensimmainen-moderni-tatuointitaiteilija/': '/fi/blog/',
    '/design-osana-strategiaa-top-5-esimerkit/': '/fi/blog/design-osana-strategiaa-top-5-esimerkitfi/',
    '/designin-tulee-olla-kaiken-ytimessa-v-2/': '/fi/blog/designin-tulee-olla-kaiken-ytimessa-v-2fi/',
    '/miksi-mvp-on-menestyksen-perusta/': '/fi/blog/miksi-mvp-on-menestyksen-perustafi/',
    '/kaytettavyys-muista-ainakin-nama/': '/fi/blog/kaytettavyys-muista-ainakin-namafi/',
    '/voittava-asiakaskokemus/': '/fi/blog/voittava-asiakaskokemusfi/',
    '/dieter-rams-ja-10-hyvan-muotoilun-periaatetta/': '/fi/blog/dieter-rams-ja-10-hyvan-muotoilun-periaatettafi/',
    '/suunnittele-kuin-jony-ive/': '/fi/blog/suunnittele-kuin-jony-ivefi/',
    '/digitalisaation-megatrendit-muokkaavat-liiketoimintaa/': '/fi/blog/digitalisaation-megatrendit-muokkaavat-liiketoimintaafi/',
    '/designin-tulee-olla-kaiken-ytimessa/': '/fi/blog/designin-tulee-olla-kaiken-ytimessafi/',
    '/palvelupolun-visualisointi/': '/fi/blog/palvelupolun-visualisointifi/',
    '/mita-hyotya-on-palvelumuotoilusta/': '/fi/blog/mita-hyotya-on-palvelumuotoilustafi/',
    '/ui-ux-suunnittelija-joka-ymmartaa-koodia/': '/fi/blog/ui-ux-suunnittelija-joka-ymmartaa-koodiafi/',
    '/category/design/': '/fi/blog/',
    '/tiimi/': '/fi/blog/',
    '/palvelumuotoilua-kiintealla-kuukausihinnalla/': '/fi/blog/palvelumuotoilua-kiintealla-kuukausihinnallafi/',
    '/kayttoliittymasuunnittelu-10-huomiota/': '/fi/blog/kayttoliittymasuunnittelu-10-huomiotafi/',
    '/category/asiakaskokemus/': '/fi/blog/',
    '/miksi-panostaa-ux-suunnitteluun-myos-sisaisissa-jarjestelmissa/': '/fi/blog/miksi-panostaa-ux-suunnitteluun-myos-sisaisissa-jarjestelmissafi/',
    '/uuden-tuotteen-muotoilu-mita-ottaa-huomioon/': '/fi/blog/uuden-tuotteen-muotoilu-mita-ottaa-huomioonfi/',
    '/valon-ja-betonin-mestari-tadao-ando/': '/fi/blog/valon-ja-betonin-mestari-tadao-andofi/',
    '/design-osana-saas-yrityksen-asiakaskokemusta/': '/fi/blog/design-osana-saas-yrityksen-asiakaskokemustafi/',
    '/miksi-rakentaisit-verkkopalvelun-wordpressilla/': '/fi/blog/miksi-rakentaisit-verkkopalvelun-wordpressillafi/',
    '/category/blog/': '/fi/blog/',
    '/digiprojektin-budjetointi/': '/fi/blog/digiprojektin-budjetointifi/',
    '/palvelut/designops/': '/fi/services',
    '/miksi-ux-suunnitteluun-kannattaa-panostaa/': '/fi/blog/miksi-ux-suunnitteluun-kannattaa-panostaafi/',
    '/design-ops/': '/fi/services',
    '/kayttojarjestelmien-sota/': '/fi/blog/kayttojarjestelmien-sotafi/',
    '/ui-suunnittelijan-tyokalupakki/': '/fi/blog/ui-suunnittelijan-tyokalupakkifi/',
    '/tulevaisuuden-kayttoliittymat/': '/fi/blog/tulevaisuuden-kayttoliittymatfi/',
    '/rakenna-palveluita-kuten-netflix/': '/fi/blog/rakenna-palveluita-kuten-netflixfi/',
    '/design-as-a-service-vs-perinteinen-design-toiminta/': '/fi/blog/design-as-a-service-vs-perinteinen-design-toimintafi/',
    '/ux-suunnittelun-salainen-arkku/': '/fi/blog/ux-suunnittelun-salainen-arkkufi/',
    '/saavutettavuusvaatimukset-digipalveluissa/': '/fi/blog/saavutettavuusvaatimukset-digipalveluissafi/',
    '/verkkopalvelun-uudistaminen/': '/fi/blog/verkkopalvelun-uudistaminenfi/',
    '/saas-yrityksen-kansainvalistyminen-ja-ux/': '/fi/blog/saas-yrityksen-kansainvalistyminen-ja-uxfi/',
    '/nain-huomioit-eettisyyden-digitaalisten-palveluiden-kehityksessa/': '/fi/blog/nain-huomioit-eettisyyden-digitaalisten-palveluiden-kehityksessafi/',
    '/mika-on-vaikeinta-ux-suunnittelussa/': '/fi/blog/mika-on-vaikeinta-ux-suunnittelussafi/',
    '/kayttoliittymasuunnittelu-osana-kasvua/': '/fi/blog/kayttoliittymasuunnittelu-osana-kasvuafi/',
    '/ohjelmistokehityksen-yleisimmat-ongelmat/': '/fi/blog/ohjelmistokehityksen-yleisimmat-ongelmatfi/',
    '/asiakasymmarrys-ja-hyva-ux/': '/fi/blog/asiakasymmarrys-ja-hyva-uxfi/',
    '/linkedin-on-myyntikanavien-ykkonen/': '/fi/blog/linkedin-on-myyntikanavien-ykkonenfi/',
    '/kayttoliittymasuunnittelu-kayttokokemuksen-avain/': '/fi/blog/kayttoliittymasuunnittelu-kayttokokemuksen-avainfi/',
    '/brandi-kansainvalistymisen-tukena/': '/fi/blog/brandi-kansainvalistymisen-tukenafi/',
    '/palvelut/design-as-a-service/': '/fi/services/',
    '/121-ideaa-verkkokauppaan/': '/fi/blog/121-ideaa-verkkokauppaanfi/',
    '/hyva-suunnittelu-mahdollistaa-kasvua/': '/fi/blog/hyva-suunnittelu-mahdollistaa-kasvuafi/',
    '/ux-suunnittelu-kaikki-paitsi-kaytettavyys-on-turhaa/': '/fi/blog/ux-suunnittelu-kaikki-paitsi-kaytettavyys-on-turhaafi/',
    '/ohjelmistokehityksen-tukeminen-designin-avulla/': '/fi/blog/ohjelmistokehityksen-tukeminen-designin-avullafi/',
    '/kayttoliittymasuunnittelu-ja-hyva-ux/': '/fi/blog/kayttoliittymasuunnittelu-ja-hyva-uxfi/',
    '/palvelumuotoilu-miksi-tarkeaa-tuoteomistajalle/': '/fi/blog/palvelumuotoilu-miksi-tarkeaa-tuoteomistajallefi/',
    '/kaytettavyys-ja-hakukoneoptimointi/': '/fi/blog/kaytettavyys-ja-hakukoneoptimointifi/',
    '/kayttokokemus-varmistaa-asiakastyytyvaisyyden/': '/fi/blog/kayttokokemus-varmistaa-asiakastyytyvaisyydenfi/',
    '/miten-tuotetaan-maailmanluokan-ux/': '/fi/blog/miten-tuotetaan-maailmanluokan-uxfi/',
    '/pakkaussuunnittelun-10-kaskya/': '/fi/blog/pakkaussuunnittelun-10-kaskyafi/',
    '/ain-hyodyntaminen-palveluissa/': '/fi/blog/ain-hyodyntaminen-palveluissafi/',
    '/palvelut/projektit/': '/fi/services/',
    '/ota-yhteytta/': '/fi/contact/',
    '/mihin-palvelumuotoilua-voi-hyodyntaa/': '/fi/blog/mihin-palvelumuotoilua-voi-hyodyntaafi/',
    '/jakobs-law-intuitiivisen-kayttoliittymasuunnittelun-kulmakivi/': '/fi/blog/jakobs-law-intuitiivisen-kayttoliittymasuunnittelun-kulmakivifi/',
    '/blog/kayttoliittymasuunnittelun-sietamaton-keveys/': '/fi/blog/kayttoliittymasuunnittelun-sietamaton-keveysfi/',
    '/palvelut/ui-ux-suunnittelu/': '/fi/services/',
    '/palvelut/good-ux-academy/': '/fi/services/',
    '/nain-varmistat-laadukkaan-kayttokokemuksen/': '/fi/blog/nain-varmistat-laadukkaan-kayttokokemuksenfi/',
    '/palvelut/palvelumuotoilu/': '/fi/services/',
    '/blog/hakukoneoptimointi-osana-verkkosivuston-suunnittelua/': '/fi/blog/hakukoneoptimointi-osana-verkkosivuston-suunnitteluafi/',
    '/empatiakartta-esimerkki-palvelumuotoilu/': '/fi/blog/empatiakartta-esimerkki-palvelumuotoilufi/',
    '/palvelumuotoilun-suurimmat-haasteet/': '/fi/blog/palvelumuotoilun-suurimmat-haasteetfi/',
    '/designops-for-saas/': '/fi/services/',
    '/mista-kayttoliittymasuunnittelijan-paiva-koostuu/': '/fi/blog/mista-kayttoliittymasuunnittelijan-paiva-koostuufi/',
    '/uxr-eli-user-experience-research/': '/fi/blog/uxr-eli-user-experience-researchfi/',
    '/design-for-saas/': '/fi/services/',
    '/hyva-suuunnittelu-mahdollistaa-kasvua/': '/fi/blog/hyva-suuunnittelu-mahdollistaa-kasvuafi/',
    '/palvelun-face-lift-10-vinkkia/': '/fi/blog/palvelun-face-lift-10-vinkkiafi/',
    '/projektit/': '/fi/references/',
    '/palvelut/lisapalvelut/': '/fi/services/',
    '/category/blog/page/2/': '/fi/blog/',
    '/suunnittelijan-rooli-ja-identiteetti-digitaalisessa-maailmassa/': '/fi/blog/suunnittelijan-rooli-ja-identiteetti-digitaalisessa-maailmassafi/',
    '/palvelut/': '/fi/services'
  },
  vite: {
    plugins: [tailwindcss()]
  }
});